#!/bin/sh

ENABLED=yes
PROCS=php8-fpm
ARGS="--daemonize --fpm-config /opt/etc/php8-fpm.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
