#!/bin/sh

ENABLED=yes
PROCS=i2pd
ARGS="--conf=/opt/etc/i2pd.conf --pidfile=/opt/var/run/i2pd.pid --logfile=/opt/var/log/i2pd.log --daemon --service"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
