#!/bin/sh
#
# Simple wrapper script which allows us to build dbus without general x support
# If an application needs x support in dbus-launch it has to depend on the
# dbus-launch-x package. The script is used to prefer dbus-launch with x over
# the dbus-lauch without x.

if [ -f /opt/bin/dbus-launch-x ]; then
	exec /opt/bin/dbus-launch-x "$@"
else
	exec /opt/bin/dbus-launch.real "$@"
fi
