#!/bin/sh

ENABLED=yes
PROCS=transmission-daemon
ARGS="-g /opt/etc/transmission"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

TRANSMISSION_WEB_HOME="/opt/share/transmission/web"

. /opt/etc/init.d/rc.func
