#!/bin/sh

export  AUTOSSH_PORT="3333"
export  AUTOSSH_GATETIME="0"
export  AUTOSSH_PATH="/opt/sbin/ssh"
ENABLED=yes
PROCS=autossh
ARGS="-f user@ssh_host -i your_private_ssh_key_file_name -N ssh_port_forwarding_options"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
