#!/bin/sh

ENABLED=yes
PROCS=gerbera
ARGS="-l /opt/var/log/gerbera.log -m /opt/etc/gerbera"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
