#!/bin/sh

ENABLED=yes
PROCS=smartdns
ARGS="-c /opt/etc/smartdns/smartdns.conf -p /opt/var/run/smartdns.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
