#!/bin/sh

ENABLED=yes
PROCS=sockd
ARGS="-f /opt/etc/sockd.conf -p /opt/var/run/sockd.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
