#!/bin/sh

ENABLED=yes
PROCS=gpsd
ARGS="-n -P /opt/var/run/gpsd.pid -S 2947 /dev/ttyUSB0"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
