#!/bin/sh

ENABLED=yes
PROCS=ser2net
ARGS="-u -P /opt/var/run/ser2net.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
