#!/bin/sh

ENABLED=yes
PROCS=hev-socks5-tunnel
ARGS="/opt/etc/$PROCS/main.yml"
PREARGS=""
DESC=$PROCS

PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
