#!/bin/sh

ENABLED=yes
PROCS="ipsec"
ARGS=""
DESC="strongSwan IPsec"

PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PROGS="/opt/sbin/$PROCS"

start() {
  $PROGS start
}

stop() {
  $PROGS stop
}

restart() {
  $PROGS restart
}

reload() {
  $PROGS update
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		restart
	;;
	reload)
		reload
	;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload]"
		exit 1
	;;
esac
exit 0
