#!/bin/sh

PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

start() {
	ipsec start
}

stop() {
	ipsec stop
}

restart() {
	ipsec restart
}

reload() {
	ipsec update
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	reload)
		reload
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload]"
		exit 1
esac
exit 0
