#!/bin/sh

. /opt/etc/config/https-dns-proxy

ENABLED=yes
PROCS=https-dns-proxy
ARGS="$OPTIONS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
