#!/bin/sh

ENABLED=yes
PROCS=umurmurd
ARGS="-c /opt/etc/umurmur/umurmur.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
