#!/bin/sh

ENABLED=yes
PROCS=chronyd
ARGS=""
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

chmod 750 /opt/var/run/chrony

. /opt/etc/init.d/rc.func
