#!/bin/sh

[ -f /opt/etc/config/ntpd ] && . /opt/etc/config/ntpd

ENABLED=yes
PROCS=ntpd
ARGS="-c /opt/etc/ntp.conf -p /opt/var/run/ntpd.pid -g $OPTIONS"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
