#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sbin:/opt/bin \
HOME=/root \
SHELL=/bin/bash \
TERMINFO=/usr/share/terminfo \
TEMP=/tmp \
TMP=/tmp \
`which chroot` /opt/debian /bin/bash
